# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d488b94a49333de25dad9a4b3e8348575fe82a1bfef06f8b7472345546f758fa07af681f52861d593e112081af678cf0e548535831d3d8aad31d54419bf7ae5

test:
  secret_key_base: 2a57e6818e7d6059d8d27388fb78be8d7a9a472b928982b2044b8d1f827f5d2f05284808376cb19ac3b4125f4257e4133bcd5919038477bef93960fd212d4a33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
